### ISSUE TITLE
What about sublime text 3 version of plugin?

### ISSUE THREAD

**Issue by oleksandr-diudiun** [robcowie/SublimeTODO#62] opened 2013-08-26 10:27 UTC

**Comment by tbergeron** [comment] 2013-09-03 20:35
+1

**Comment by mrmartineau** [comment] 2013-09-05 05:56
+1

**Comment by jamesla** [comment] 2013-09-06 20:52
+1

**Comment by bfulop** [comment] 2013-09-11 09:41
:+1

**Comment by wadtech** [comment] 2013-09-11 15:57
+1

**Comment by bfulop** [comment] 2013-09-11 16:21
I just installed dnatag's fork on ST3 and it works great!
Thanks!

**Comment by simonluijk** [comment] 2013-09-13 15:06
dnatag's fork is also working for me.

**Comment by lizzzzard** [comment] 2013-10-22 08:09
+1

**Comment by halcarleton** [comment] 2013-10-22 11:26
The current version is working fine for me in ST3

**Comment by murrah** [comment] 2013-10-28 00:05
Just installed the current version on Windows 7 ST3 and set the "todo" config in Settings-User. I am getting the menu options to "Show TODO", but nothing happens when I execute them. I have lots of TODO strings within my comments (JavaScript). Any ideas? 

@halleycarleton: Did you need to do anything special? 

Thanks,
Murray

**Comment by halcarleton** [comment] 2013-10-28 00:25
@murrah I didn't have to do anything special. I installed sublimeTODO through "package control: add repository". Once it was installed I added the patterns object to my settings - user JSON and then just started using it with no issue. I generally use "Show TODOs: project and open files" from the command palette.

I'm not sure what you mean by 'menu options to "show TODO",' are you using the command palette(Tools > Command Palette or Ctrl+Shift+P)? Also do you have a file open when you search for the "show TODOS:" command in command palette" When I first installed it it wouldn't show the command unless a file was open, although that is no longer the case.

Finally, I am using windows 8, so maybe there is an issue with windows 7? That's a big maybe though.

**Comment by murrah** [comment] 2013-10-28 01:38
Thanks @halleycarleton. Yes that is what I have done also. Files are open, using the Ctrl+Shift+P. When I watch the status bar at the bottom of the screen, no messages appear indicating it is searching. Maybe it doesnt do that anyway. 

I am assuming that gas in the code should look like
    // TODO: Blah blah

Thanks for your response!
Go well,
Murray

**Comment by halcarleton** [comment] 2013-10-28 01:47
@murrah A message ("Finding TODOs") does show up in the status bar during searches for me, although only for a moment. Also, even if there are no TODOs found you should still be getting an empty search result tab titled "TODO_RESULTS".

Yes that is the correct syntax.

Sorry I can't be of more help.
Goodluck!

**Comment by murrah** [comment] 2013-10-29 20:37
@halleycarleton Thanks! I will post back here when I solve this. Thanks for confirming what action _should_ be happenning.

**Comment by dcbartlett** [comment] 2013-10-30 03:14
I'll donate 50$ to this port.  Can we do bountysource?

**Comment by dcbartlett** [comment] 2013-10-30 03:21
I can confirm that @dnatag 's fork does work in ST3 if you load it via the command palette.  I'd like to see it show up under **_preferences>package settings_** as well.

Side-Note: I'd also like to see a feature for right clicking on a folder and searching within that folder.  (10$) Bounty

**Comment by murrah** [comment] 2013-10-30 04:38
Thanks @dcbartlett. I installed @dnatag's fork successfully also. One issue I still have is that even though I have overridden the patterns config as shown below, it is still indexing "NOTE:" which I dont want for this project. It is definately using the user todo config because the file and folder exclusions I also added _are_ being used.
        "patterns":
        {
            "TODO": "TODO[\s]_?:+(?P<todo>._)$"
        }
I also tried adding a test custom tag:
      "AWESOME": "AWESOME[\s]_?:+(?P<awesome>\S._)$"

and it didnt index that tag where I had used it eg // AWESOME: This is a test

At least I am now getting a TODO list! Yay!

Thanks,
Murray

**Comment by wadtech** [comment] 2013-11-04 09:38
+1 for NOTE: matching despite user config override.

**Comment by axelav** [comment] 2013-12-04 21:49
thanks @dnatag, had to restart ST but then your fork works perfectly.

**Comment by chrisspiegl** [comment] 2013-12-16 09:33
+1

**Comment by quantizer** [comment] 2014-01-21 10:21
+1

**Comment by jonathanrdelgado** [comment] 2014-02-06 21:44
For all those waiting:

Went ahead and fixed all the issues and added a bunch of features today. Here is the repo: https://github.com/jonathandelgado/SublimeTodoReview - currently in line to be added to Package Control - should be there tomorrow.
- Fixed Setting Issues
- Fixed Result Navigation Issues
- Added Color Scheme Support
- Added Priority Support
- Added Tag Support

More features coming soon.

**Comment by dnatag** [comment] 2014-02-06 23:14
Initially, I thought I gonna put together something, but never had sufficient energy and time other than small bug fix. This is excellent!

**Comment by andredurao** [comment] 2014-02-11 17:27
+1

**Comment by rooc** [comment] 2014-02-13 17:14
+1

**Comment by jonathanrdelgado** [comment] 2014-02-16 03:22
My final update to this:

TodoReview is now on Package Control. @robcowie has also handed over his spot in Package Control, so any active users with SublimeTODO installed will automatically be transferred over.

If you have any questions or issues, please submit an issue over at https://github.com/jonathandelgado/SublimeTodoReview.

Thank you.

**Comment by johnathanz** [comment] 2014-10-26 01:45
confirmed works on ST3, build 3065.  Should close this issue...

**Comment by robcowie** [comment] 2014-10-26 12:58
This is no longer the active version of SublimeTODO. See https://github.com/jonathandelgado/SublimeTodoReview

**Closed as completed by robcowie** 2014-10-26 12:58 UTC
